### ISSUE TITLE
Implement validated configuration files

### ISSUE THREAD

**Issue by camirmas** [NREL/electrolyzer#11]
**Is your feature request related to a problem? Please describe.**
<A clear and concise description of the problem.>

Users need a structured way to define their Electrolyzer runs. Other NREL repos (e.g. WISDEM/WEIS/Fl) use YAML config files which are validated using JSONSchema, and `electrolyzer` would benefit from the same treatment. While we won't have a large number of configuration values to start with, this will grow in time, and starting with this approach will avoid future issues as well as provide users with a familiar interface. Additionally, defined schemas lend themselves well to auto-generated documentation.

**Describe the solution you'd like**
<A clear and concise description of what you want to happen.>

- [ ] Implement an electrolyzer configuration schema that encompasses all options for individual electrolyzers as well as control schemes for multiple electrolyzers. Use precedents set in WISDEM
- [ ] Apply schema validation prior to electrolyzer runs using `jsonschema` package
- [ ] Allow `Electrolyzer` and `ElectrolyzerSupervisor` to be instantiated via `Dict` generated from YAML config
- [ ] Add electrolyzer example runs to `examples` 

**Describe alternatives you've considered**
<A clear and concise description of any alternative solutions or features youve considered.>

The team has previously discussed the use of [attrs](https://www.attrs.org/en/stable/index.html) to define classes. This library also includes validators. However, for ease of documentation generation, we may want to rely on `jsonschema` for this. However, `attrs` might still prove useful in that we can use it for easier class instantiation as well as static type checking.

**Additional context**
<Add any other context or screenshots about the feature request here.>

**Comment by camirmas** [comment]
Here's a first take on the potential options, will update with more specific information shortly.

- electrolyzer
  - n_cells
  - cell_area
  - temperature
  - stack_rating_kW
  - dt
  - include_degradation_penalty
  - self.rf_track
  - turn_on_delay
  - tau
  - min_power
- control
  - n_stacks
  - control_type

**Comment by nRiccobo** [comment]
Would it be 1 yaml file to rule all the attributes? Or multiple depending on the context? 

After the conversation about cost modelling, I wonder how many parameters and options we would include. Just some ideas:

- Membrane cost
- Catalyst/material cost
- Interest rates
- Operating Ex
- Manufacturing cost

**Comment by camirmas** [comment]
Yes! I'd love to see this take inspiration from the [windIO](https://windio.readthedocs.io/en/latest/source/turbine.html) spec that is used in WISDEM and elsewhere. The windIO spec has a `costs` section that specifies parameters for LCOE analysis

**Comment by genevievestarke** [comment]
Just adding what we discussed on Wednesday:
 - Define a way to give electrolyzer rating (either through stack_rating_kW or a combination of n_cells and cell_area) 
 - Add max current into the inputs since it is used to get the stack rating from n_cells and cell_area
