### ISSUE TITLE
Operator/Power Manager Class 

### ISSUE THREAD

**Issue by nRiccobo** [NREL/electrolyzer#15]
@ZackTully mentioned in 11/9 weekly meeting that operations outside the electro-chemistry or controls should be handled elsewhere. There should be another class to handle some of those functions and allow us to unit test features that does necessarily involve the electrolyzer. The most prominent example is the curtail_wind_power() found in Electrolyzer which doesn't belong there and currently does not do anything. 

A separate operator class could handle various power inputs that are directed to the electrolyzer and/or the control supervisor. The operator/manager class could include: 
- Generic wind profiles
- Wind curtailment 
- OpenFAST file interpretation
- Budget the power for auxiliary models (Pumps, storage, transformers, etc)

**Comment by camirmas** [comment]
The other piece of this is to separate the stack operation from the electrochemistry itself, something that I'll be proposing with my next PR (see [branch](https://github.com/camirmas/electrolyzer/tree/attrs))

**Comment by camirmas** [comment]
I think we've covered this for now, as it sounds like BOS-type work will be handled outside of this repo
