### ISSUE TITLE
Cost model

### ISSUE THREAD

**Issue by jaredthomas68** [NREL/electrolyzer#16]
**Is your feature request related to a problem? Please describe.**
A cost model is need - CAPEX, OPEX, LCOH, etc

**Describe the solution you'd like**
New class for cost models

**Describe alternatives you've considered**
We could rely on PyFAST (internal NREL cost code with a name that needs to be changed)

**Additional context**
Work in progress

**Comment by camirmas** [comment]
I'm thinking we'll close this one once we have everything we need for v0.2.0. Here's a working list:

#44 
#45 
#47
