### ISSUE TITLE
Update Degradation Rates

### ISSUE THREAD

**Issue by ZackTully** [NREL/electrolyzer#27]
Update the degradation rates in `electrolyzer/electrolyzer.py` to better match the experimental results in

- Electrolyzer Durability at Low Catalyst Loading and with Dynamic Operation - Alia et al. - 2019
- Impact of Intermittent Operation on Lifetime and Performance of a PEM Water Electrolyzer - Weiss et al. -2019

**Comment by ZackTully** [comment]
see #30

**Comment by camirmas** [comment]
@ZackTully I recommend keeping issues open until their respective PR is merged, just for clarity. You can actually do this automatically as well by putting the following line in the body of your PR description:

resolves #27
