### ISSUE TITLE
Units in `electrolyzer_model`. 

### ISSUE THREAD

**Issue by vijay092** [NREL/electrolyzer#28]
I wanted to know what the units are for the `electrolyzer_model` function in `electrolyzer.py`. I'm guessing it is kW, C, A. Could you please confirm?

**Comment by camirmas** [comment]
Hi @vijay092, the units for that function are W, C, A. I'll add some documentation for that to the function. Also, the most up to date electrolyzer code is currently in the `develop` branch, and will soon be merged to `main`. It is much more robust, and includes more usage examples.

**Comment by vijay092** [comment]
Thanks so much!
